### ISSUE TITLE
Support Prisma client generation

### ISSUE THREAD

**Issue by ehmicky** [netlify/zip-it-and-ship-it#101]
Prisma generates its client logic during `postinstall` and outputs it to `node_modules/.prisma` (using `${__dirname}/../../.prisma`). 

This does not work with `zip-it-and-ship-it` due to the [reason outlined here](https://github.com/netlify/zip-it-and-ship-it/issues/68#issuecomment-620203164). 

We should add some logic to support Prisma's use case.

**Comment by ehmicky** [comment]
A workaround could be the following: [when we retrieve the list](https://github.com/netlify/zip-it-and-ship-it/blob/6dc9650ff273de64db2f84a03fcc0c713a7192be/src/dependencies.js#L124) of published files (`files` field from `package.json` of a Node module), we could add the following logic: if module is `@prisma/client`, then add `${__dirname}/../../.prisma` to the list of published files, providing that directory exists.

@timsuchanek, could you confirm this would work as intended?

**Comment by timsuchanek** [comment]
Thanks @ehmicky, that's exactly what we need!

**Comment by ehmicky** [comment]
Done in #103.
Could you please check the PR and make sure this is doing what you would like? Thanks!

**Comment by ehmicky** [comment]
This has been released in `@netlify/zip-it-and-ship-it@0.4.0-16`. Could you please confirm this is fixing your problem? When you do, I will release this to production.

**Comment by timsuchanek** [comment]
Thanks a lot @ehmicky for looking into this. I can confirm that this is indeed working now!
