### ISSUE TITLE
Node 16 not being used for esbuild target

### ISSUE THREAD

**Issue by Hrishikesh-K** [netlify/zip-it-and-ship-it#1137]
**- Do you want to request a _feature_ or report a _bug_?**

A bug

**- What is the current behavior?**

Even if a user has configured Node 16 to be used in their site by:

1. Setting their build's Node Version to 16 (irrelevant) OR
2. Setting their Functions' Runtime version to `nodejs16.x` (variable in UI and TOML - TOML one being irrelevant)

We still set the target as Node 14. This results in failures like [these](https://answers.netlify.com/t/60252/).

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a JS/TS file with content: `await Promise.resolve('foo')`.
2. Try bundling it with `esbuild`.

**- What is the expected behavior?**

The Function should use Node 16 if configured. Considering that's going to be the default version by next week, it's probably going to be used more.

**- Please mention your node.js, and operating system version.**

N/A

**Comment by Skn0tt** [comment]
should be addressed by https://github.com/netlify/zip-it-and-ship-it/pull/1138/files#diff-057629bd84a1bcc5521d1bd8408d75f03e622ac0234fbb6384443253c861fe78R11

**Comment by acarl005** [comment]
@Skn0tt Happy to see that is merged :) Sorry to pester, but how long after merging until this is deployed to Netlify?

**Comment by acarl005** [comment]
Thanks!
