### ISSUE TITLE
Cannot find module error with @sveltejs/adapter-netlify

### ISSUE THREAD

**Issue by mcmxcdev** [netlify/zip-it-and-ship-it#1197]
Running into failing deploys with a Sveltekit project using `@sveltejs/adapter-netlify`

Building the project locally works, building on Netlify fails, with and without cache,

**- What is the current behavior?**

Running into dependencies installation errors coming from this repo.
Note that if I install `js-yaml` as dependency, then the build fails next time with a different dependency (follow-redirects)

![Screenshot from 2022-09-05 08-43-36](https://user-images.githubusercontent.com/16797721/188381843-731e51f7-f508-4705-a81c-e4e66e0aad5f.png)

**- What is the expected behavior?**

Successful build without any hassle

**- Please mention your node.js, and operating system version.**

Node v16.16.0
Manjaro Linux

**Comment by danez** [comment]
Sorry for the very late reply. Is this still an issue?

I cannot really say what is going on, but I see you are using pnpm and we now have first class support for it, so there is not need to call `npx pnpm install` or `npx pnpm` yourself.

Checkout this for more info: https://www.netlify.com/blog/how-to-use-pnpm-with-netlify-build/

Hope that helps!

If you are still running into this problem, would you be able to create an example site, so I can try to reproduce?

**Comment by mcmxcdev** [comment]
Haven‘t encountered it in a while, gonna close it.

**Comment by dtinth** [comment]
I get similar errors but with different package name (`loose-envify` and `object-assign`). I had to add `shamefully-hoist=true` to `.npmrc` to get the project to build successfully on Netlify.
