### ISSUE TITLE
Doesn't work with `optipng-bin`

### ISSUE THREAD

**Issue by danoc** [netlify/zip-it-and-ship-it#36]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
`zip-it-and-ship-it` does not work with `optipng-bin`. I got the following error when trying to use `imagemin-optipng` with Netlify Functions:

```
{"errorMessage":"spawn /var/task/node_modules/optipng-bin/vendor/optipng
 ENOENT","errorType":"Error","stackTrace":["_errnoException 
(util.js:1022:11)","Process.ChildProcess._handle.onexit 
(internal/child_process.js:190:19)","onErrorNT 
(internal/child_process.js:372:16)","_combinedTickCallback 
(internal/process/next_tick.js:138:11)","process._tickDomainCallback 
(internal/process/next_tick.js:218:9)"]}
```

After debugging, I've realized that this is happening because:

1. `imagemin-optipng` depends on `optipng-bin`.
2. `optipng-bin` ships with compiled binaries but, if those don't work, it downloads a `tar.gz` and compiles it as part of a `postinstall` hook.
3. `optipng-bin` stores the binary in its `vendor` folder. The path looks like this: `node_modules/optipng-bin/vendor/optipng`.
4. `zip-it-and-ship-it` goes through each dependency and uses `npm-packlist` to decide which files to keep.
5. `npm-packlist` uses the `files` property of `package.json` files to decide which files to keep.
6. `optipng-bin` doesn’t include the `vendor` folder in the `files` property of `package.json` so the compiled binary never makes it into the zip file that `zip-it-and-ship-it` creates.

**- If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**- What is the expected behavior?**

N/A

**- Please mention your node.js, and operating system version.**

Latest OS X, Node v8

***

I'd argue that this is more of an issue with `optipng-bin` than `zip-it-and-ship-it`, but I wanted to create this so that others don't get stuck on this in the future.

The workaround I've created is to run this command before `zip-it-and-ship-it` runs:

```bash
npx json -I -f ./node_modules/optipng-bin/package.json -e 'this.files=["index.js","cli.js","lib","vendor"]'
```

This adds `vendor` as a folder in the `files` property of `optipng-bin`.

If you're using this with Netlify, your build command in `netlify.toml` would look like this:

```toml
[build]
  # publish = "."
  # functions = "function/"
  command = "yarn install && npx json -I -f ./node_modules/optipng-bin/package.json -e 'this.files=[\"index.js\",\"cli.js\",\"lib\",\"vendor\"]'"
```

**Comment by sw-yx** [comment]
thanks for the very comprehensive report! yeah our reliance on the `files` field will probably hurt us when people use nonconformant packages and think it is our fault. something to think about but we probably wont change anything soon.

instead of running your script you might consider using patch package https://github.com/ds300/patch-package
