### ISSUE TITLE
usage with yarn workspaces

### ISSUE THREAD

**Issue by tibotiber** [netlify/zip-it-and-ship-it#37]
**- Do you want to request a *feature* or report a *bug*?**
bug / better docs

**- What is the current behavior?**
From what I understand, using zisi with [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) does not work due to the hoisting of modules causing a module to potentially be higher in the tree than the `package.json` it was declared in. The problem and potential solution are described [here](https://yarnpkg.com/blog/2018/02/15/nohoist/).

To be more precise, I have tried to add to the root `package.json`:
```
  "workspaces": {
    "packages": [
      "A",
      "B",
      "functions"
    ],
    "nohoist": [
      "functions/**"
    ]
  },
```
and to the `package.json` of my functions:
```
  "private": true,
  "workspaces": {
    "nohoist": [
      "**"
    ]
  },
```

I can confirm that no module in the functions directory is hoisted after that. However my deploy still fails with the following error:
```
12:34:14 AM: Function Dir: /opt/build/repo/functions/dist
12:34:14 AM: TempDir: /tmp/zisi-857404437
12:34:15 AM: Prepping functions with zip-it-and-ship-it 0.3.1
12:34:34 AM: [ { path: '/tmp/zisi-857404437/health.zip', runtime: 'js' },
12:34:34 AM:   { path: '/tmp/zisi-857404437/process3dModel.zip',
12:34:34 AM:     runtime: 'js' } ]
12:34:34 AM: Prepping functions complete
[...]
12:34:34 AM: Build script success
12:34:34 AM: Starting to deploy site from 'studio/build'
12:34:34 AM: Creating deploy tree 
12:34:34 AM: 0 new files to upload
12:34:34 AM: 2 new functions to upload
12:36:56 AM: Failed to upload file: &{Name:process3dModel Sum:15bec3b5d5780a2927fdb3d879651765dd97f9adcaab59915caf184e81eadc27 Runtime:js Size:<nil> Path: Buffer:0xc000934000}
12:37:04 AM: Failed to upload file: &{Name:health Sum:c3f2203387ca2e24ec3d20d8c27359ee1b8e49e2787bba658975267c978ae874 Runtime:js Size:<nil> Path: Buffer:0xc0001f6330}
12:37:04 AM: failed during stage 'deploying site': Failed to execute deploy: Upload cancelled: health
12:37:04 AM: Failing build: Failed to deploy site
12:37:05 AM: Finished processing build request in 6m21.830165011s
```

I have also tried to clear cache and deploy again, same fate. Any idea? Especially what does `Size:<nil>` mean?

The functions work using Netlify Dev.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Try to deploy functions in a repo using yarn workspaces.

**- What is the expected behavior?**
It just works TM 😬

**- Please mention your node.js, and operating system version.**
Happens in Netlify build.

**Comment by tibotiber** [comment]
Hello, gentle ping if anyone can point me in a direction to try and resolve this? How would I get more debug logged? Thanks.

**Comment by tibotiber** [comment]
After further tests, I don't think this is yarn workspaces related. 
For full transparency, I have posted for some help from the community at https://community.netlify.com/t/functions-failed-to-upload-file/2088 just now.

**Comment by ehmicky** [comment]
Hi @tibotiber, sorry for the late response.

There's a PR at #49 that might solve this issue. The PR preserves the source directory structure. Once this is merged and deployed, I'll check with you to confirm whether this bug is still happening.

**Comment by tibotiber** [comment]
Hi @ehmicky, thanks for your help and sorry for not updating here. I kinda forgot I had ever posted this issue. This was solved in https://community.netlify.com/t/functions-failed-to-upload-file/2088/14 and was related to a AWS limitation on maximum length of environment variables. :)

**Comment by ehmicky** [comment]
Great, glad this is fixed! Feel free to reach out again if you have other issues.
