### ISSUE TITLE
Zipped subdirectories paths seem incorrect

### ISSUE THREAD

**Issue by peterp** [netlify/zip-it-and-ship-it#38]
I'm transpiling a lambda function using babel which is built into `dist/functions/test.js`. 

<img width="277" alt="image" src="https://user-images.githubusercontent.com/44849/63329884-0ff56680-c333-11e9-8bac-7cce88de0f72.png">

`test.js` requires code from another directory: `var _auth = require("../lib/auth0");`

I'm [packaging this function with ZISI](https://github.com/hammerframework/billable/blob/9b561f715c7a757db4e834e2207db40392b5b744/api/scripts/package-functions.js#L1-L32), and the resulting zip file has this content:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/44849/63329497-5bf3db80-c332-11e9-919b-006c58600249.png">

Based on the screenshot above the problem seems that the paths are incorrect when trying to [execute the function](https://5d5ba8e475cf20b485c487ec--sleepy-chandrasekhar-b9d767.netlify.com/.netlify/functions/test):

```json
{"errorMessage":"Cannot find module '../lib/auth0'","errorType":"Error","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)","Object.<anonymous> (/var/task/test.js:8:13)","Module._compile (module.js:652:30)","Object.Module._extensions..js (module.js:663:10)","Module.load (module.js:565:32)","tryModuleLoad (module.js:505:12)","Function.Module._load (module.js:497:3)"]}
```

Am I thinking about ZISI incorrectly?

**Comment by ehmicky** [comment]
Fixed by #48.

**Comment by ehmicky** [comment]
This fix should also be available in our [new Build beta](https://www.netlify.com/build/plugins-beta/) if you want to try it out :)

**Comment by danoc** [comment]
> This fix should also be available as part of our [new Build beta](https://www.netlify.com/build/plugins-beta/) if you want to try it out :)

Cool! How does this relate to Netlify Build Plugins though? Is that infrastructure using a pre-release version of `zip-it-and-ship-it`?

**Comment by ehmicky** [comment]
Yes exactly, the new Netlify Build includes several features, including Netlify Plugins. It uses the pre-release version of `zip-it-and-ship-it`.
