### ISSUE TITLE
Flag bundling errors as user errors

### ISSUE THREAD

**Issue by eduardoboucas** [netlify/zip-it-and-ship-it#384]
**- Do you want to request a _feature_ or report a _bug_?**

🐞 

**- What is the current behavior?**

Errors resulting from bundling a function with esbuild are flagged as unhandled errors.

**- What is the expected behavior?**

These errors should be flagged as user errors.

**- Please mention your node.js, and operating system version.**

N/A

**Comment by ehmicky** [comment]
Progress at https://github.com/netlify/build/pull/2419 and https://github.com/netlify/build/pull/2420
