### ISSUE TITLE
Add support for source maps

### ISSUE THREAD

**Issue by eduardoboucas** [netlify/zip-it-and-ship-it#414]
**- Do you want to request a _feature_ or report a _bug_?**

Feature.

**- What is the expected behavior?**

When using functions created by `zip-it-and-ship-it` for local development, it would be useful to have access to source maps to ease debugging.

We could add a `sourcemap` configuration property, which could potentially be enabled by default when `archiveType` is `none`.

This would improve the experience of serving bundled functions in the CLI (https://github.com/netlify/cli/pull/2094).

**Comment by erezrokah** [comment]
Also related to https://github.com/netlify/netlify-lambda/issues/262 and https://github.com/netlify/cli/issues/409

**Comment by ehmicky** [comment]
This is a good idea.

Since this would impact the archive size significantly, disabling by default when `archiveType` is `zip` and enabling when `none` make sense too.

Source maps have many things that can be configured: separate file vs inline comment, URI resolution, etc. I think it might be nice to start with making those choices on user's behalf until someone files an issue asking for more flexibility. In other terms, making `sourcemap` a boolean. What do you think?

**Comment by eduardoboucas** [comment]
> enabling it by default when none make sense too (since none is only meant for local usage, i.e. not uploaded to AWS Lambda, is that correct?).

That's what it was built for, yes. But perhaps there are other use cases for it that we're not considering. For example, someone might want to add additional files to the bundled functions, in which case it would probably be more efficient to generate a directory, add the files and then handle the zip creation on their end, as opposed to unzipping, adding the files and then creating another zip.

This is probably an edge case, but assuming that `archiveType: "none"` is for local development only may be a flawed assumption, so I'm leaning towards making the source map generation always disabled by default. Something to think about!

> Source maps can be configured in many ways: separate file vs inline comment, URI resolution, etc. I think it might be nice to start with making those choices on users' behalf until someone files an issue asking for more flexibility. In other terms, making sourcemap a boolean. What do you think?

Absolutely! Let's start with the simplest possible implementation and iterate from there.
