### ISSUE TITLE
Why is the `skipGo` default value different on the CLI and programmatically?

### ISSUE THREAD

**Issue by ehmicky** [netlify/zip-it-and-ship-it#50]
The `skipGo` parameter default value is `true` when `zip-it-and-ship-it` is called via the binary, but it's `false` when called programmatically. Is this intended? For reference that parameter determines whether the Go binaries are zipped or simply copied.

@DavidWells @biilmann @sw-yx

**Comment by DavidWells** [comment]
This might have something to do with how it is currently used in https://github.com/netlify/buildbot
