### ISSUE TITLE
Error occurs when plugin uses listAll to get list of modules from typescript file

### ISSUE THREAD

**Issue by yongwee** [netlify/zip-it-and-ship-it#512]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
Error: Could not list Netlify Functions files

I am using  the `netlify-plugin-inline-functions-env` plugin which [calls `functions.listAll`](https://github.com/bencao/netlify-plugin-inline-functions-env/blob/c3866ce029bb93b35ed3000e554be8c85be8892a/index.js#L36) that's passed in by the netlify builder. The function call produces the above-mentioned error when a `ts` function file is importing another `ts` file.
```
import example from '../utils/example'; // importing from `../utils/example.ts` produces the error
```

I did some code tracing and believe this is the offending line: https://github.com/netlify/zip-it-and-ship-it/blob/57e57ab3397b6e4eeac5f787537dfdfdf31c3c72/src/runtimes/node/src_files.js#L47
(If I comment out that line the build succeeds locally)
Not quite sure why it is defaulting to the legacy bundler, I believe the default bundler is supposed to be esBuild now?

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Add `netlify-plugin-inline-functions-env` plugin for netlify builds
2.  Write a function in `.ts` e.g. `main.ts`
3. Write another helper module e.g. `../utils/example.ts`
4. Import module within `main.ts` e.g. `import example from '../utils/example.ts'`
5. run `netlify build`

This will trigger an error during the inlining because it uses the `listAll` function injected from within this repo.

**- What is the expected behavior?**
Build successfully completes.

**- Please mention your node.js, and operating system version.**
node v12.16.1
MacOS v11.3.1

**Comment by alexjfno1** [comment]
@yongwee I have the same issue, if you comment out the offending line my build passes too but it doesn't actually sub out the `process.env.FOO` for any value. Can you confirm that it works correctly for you when you comment out the line?

**Comment by eduardoboucas** [comment]
@yongwee @alexjfno1 This should be fixed in the latest versions of `@netlify/zip-it-and-ship-it`, `@netlify/build` and `netlify-cli`. If you still see this error after upgrading, please reply in this issue and I'll reopen.

Thanks! 🙌🏻

**Comment by yongwee** [comment]
@alexjfno1 sorry didn't get to replying your comment earlier. I havent actually looked at the results of the build but I reckon swapping it out for esmodule bundler would've worked ... ...? Not quite sure myself 🤔 

@eduardoboucas just tried doing some test builds within netlify itself and it seems to work!
One side effect i've noticed is that env vars provided by netlify like `CONTEXT` and `BUILD_ID` no longer get swapped in for `ts` files tho while it continues to work for `js` files, but other user-defined env vars do work on both (which is good enough for me at this stage).
Anw thanks for fixing it!

**Comment by alexjfno1** [comment]
@eduardoboucas Thanks for picking this up, it is indeed working for me now 👍
