### ISSUE TITLE
Feature request: could it be possible to pass the define option to esbuild? 👀

### ISSUE THREAD

**Issue by zoexx** [netlify/zip-it-and-ship-it#584]
Hi there, I almost spend a day to find the inline env solution for functions write in typescript and build with `esbuild`.

currently, the function runtime could only work with defined envs on netlify UI. But that could not support multiple environment, such as `production` and `staging`.

`netlify-plugin-inline-functions-env` is quite popular to inline the envs, but it could not work with `.ts` files with `esbuild`.

I noticed that the [define option of esbuild](https://esbuild.github.io/api/#define) is what just I want, no need any other plugins to reslove the issue.

Could it be possible to pass the define options to `esbuild` via `netlify.toml`?

Cute animal
```
  //
 ('>
 / rr
*\))_
```

**Comment by eduardoboucas** [comment]
Hi @zoexx. Apologies for the late reply.

We're currently working on a solution to allow tapping into esbuild's `define` via a configuration property, just like you described. I'll update this issue with more details when I have them.

Thanks!
