### ISSUE TITLE
Allow `.mjs` entrypoints for functions

### ISSUE THREAD

**Issue by ascorbic** [netlify/zip-it-and-ship-it#588]
**- Do you want to request a _feature_ or report a _bug_?**

Feature

**- What is the current behavior?**

While zisi can bundle ESM files with`.mjs` extensions, it does not recognize them as entrypoints.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a function in `netlify/functions/hello/hello.mjs`
2. Run `zip-it-and-ship-it netlify/functions out_functions`

**- What is the expected behavior?**
The function `hello` is bundled, defaulting to esbuild

**Comment by klavavej** [comment]
marking this `needs docs` as I think we should probably update the javascript function docs to reflect this new capability
