### ISSUE TITLE
netlify.toml : included_files not able to reference files outside base_dir but still in repo

### ISSUE THREAD

**Issue by LudwigK9** [netlify/zip-it-and-ship-it#609]
**Describe the bug**

In a (mono)repo with a configured base directory in build settings, it is not possible to include files in another folder than the base directory (such as a sibling folder).

**To Reproduce**

Set up a site in Netlify, set a base directory, try setting `included_files = ['../shared/locales/**', ]` in `netlify.toml` and you will get an error: `Configuration property functions.*.included_files[0] must be inside the root directory.` .

**Configuration**

netlify.toml: 
```
[build]
  command = "yarn build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ['../shared/locales/**', ]
```

**Expected behavior**

It should be able to include files from the entire repo, and not just the specified base_dir.

**Comment by ehmicky** [comment]
Thanks for reporting this @LudwigK9!

This appears to be a bug. I reported it at https://github.com/netlify/build/issues/3431 to see if someone from our team sees a reason behind the current behavior. If not, I will fix it. :+1:

**Comment by LudwigK9** [comment]
What a response! Thank you for looking into this @ehmicky . 👍

**Comment by ehmicky** [comment]
PR to fix it at https://github.com/netlify/build/pull/3598

**Comment by ehmicky** [comment]
This should be fixed now! :tada:
