### ISSUE TITLE
Add `size` property to output of `zipFunction` and `zipFunctions`

### ISSUE THREAD

**Issue by eduardoboucas** [netlify/zip-it-and-ship-it#620]
**- Do you want to request a _feature_ or report a _bug_?**

A feature. 🚀 

**- What is the expected behavior?**

zip-it-and-ship-it should return the size of the archives it creates, allowing consumers (e.g. Netlify Build) to warn users whenever the size of a function is above a pre-configured threshold. This is particularly relevant to flag problems with functions that exceed the 50MB limit of AWS Lambda.

**Comment by rjbeers** [comment]
@eduardoboucas please update the description to include the value of displaying the size in the logs. Suggesting esbuild if the size is large could be an option.

**Comment by eduardoboucas** [comment]
> @eduardoboucas please update the description to include the value of displaying the size in the logs. Suggesting esbuild if the size is large could be an option.

I've added this context in https://github.com/netlify/build/issues/3554, because there are two parts to this work:

1. Surfacing that information via a new property in `zip-it-and-ship-it`
2. Reading that and showing the error/warning in Netlify Build
