### ISSUE TITLE
JS & Go function collisions

### ISSUE THREAD

**Issue by DavidWells** [netlify/zip-it-and-ship-it#72]
https://twitter.com/chrisbiscardi/status/1198556686677528576

It looks like if users use Go & JS functions in a project something is trying to automatically wrap functions in a JS module.

This isn't visible on live build using `ZIP_IT_AND_SHIP_IT_VERSION 0.3.1` but this behavior is visible in the Build Beta using a newer version  https://github.com/netlify/build/blob/master/packages/build/package.json#L28

This appears to be a regression in how the bundling worked in previous versions

**Comment by ehmicky** [comment]
Hi @ChristopherBiscardi, thanks a lot for reaching out about this bug!

I have looked at the current code but cannot find where this problem might come from. Could you please describe your `functions` directory structure (including filenames)? Thanks a lot!

**Comment by ChristopherBiscardi** [comment]
hey @ehmicky My filesystem looks like this after the go bins are built and js deps installed. I don't do anything after it looks like this and there is no JS build process that I invoke.

```
functions
├── go-test
├── some-other-go-binary
└── graphql
    ├── graphql.js
    ├── graphql.test.js
    ├── node_modules
    ├── package.json
    └── yarn.lock
```

**Comment by ehmicky** [comment]
Thanks a lot!

This directory structure looks pretty standard. I've tried replicating it locally but both Go and Node.js functions are building correctly for me.

Would it be possible for you to provide with a demo repository (or link to an existing repository with this problem) by any chance?

**Comment by ehmicky** [comment]
@ChristopherBiscardi We have just fixed some issues related to Go functions. Could you check whether this is fixing your issue? Thanks!

**Comment by ehmicky** [comment]
@ChristopherBiscardi We have just fixed Go Functions support in the Netlify Build beta (https://github.com/netlify/zip-it-and-ship-it/pull/89), could you confirm this fixes your problem?
