### ISSUE TITLE
Purge dependencies which are not called in runtime

### ISSUE THREAD

**Issue by kripod** [netlify/zip-it-and-ship-it#73]
When bundling a project with `prisma2` included as a dependency, a very large bundle (>50MB) gets generated, which [may not be uploaded to AWS Lambda](https://community.netlify.com/t/cannot-upload-build-function-to-aws-lambda/5261/4?u=kripod). While `prisma2` is used for generating files during build time, it isn't depended upon in runtime.

As mentioned [here](https://github.com/netlify/zip-it-and-ship-it/issues/68#issuecomment-550430607), inclusion and exclusion of modules should be possible. By default, files referred _(transitively)_ by `bin` inside the `package.json` of each dependency should be excluded.

**Comment by DavidWells** [comment]
Hey @kripod sorry for the troubles! We need something in functions configuration to take this into account.

The reverse will also be true, where functions use the `bin` in the function execution and users do want it uploaded. 

This will probably materialize something like as advanced function configuration

```yml
build:
  functions:
    dir: /path/to/functions/folder
    exclude: 
      - **/**/node_modules/bin/prisma2
```

--- 

For now, you would need to manually zip up the function, excluding the files you don't want & overwrite the `function-name.zip` that gets generated in a `postBuild` script

**Comment by kripod** [comment]
Thank you for the quick response! I'm trying to mitigate this issue from multiple sides, see #74 and https://github.com/prisma/photonjs/pull/313.

**Comment by ehmicky** [comment]
As @DavidWells is mentioning, the real fix for this issue would be the possibility to explicitly exclude specific node modules from the bundles, as outlined in #68.

I've just implemented a temporary workaround available in [`zip-it-and-ship-it@0.4.0-8`](https://github.com/netlify/zip-it-and-ship-it/releases/tag/v0.4.0-8) in the meantime, that should solve your specific case. This fix should also be available in our [new Build beta](https://www.netlify.com/build/plugins-beta/).

**Comment by kripod** [comment]
Whoa, thank you for the fix! I’m closing this issue, eagerly waiting for the “real” workarounds described above.

**Comment by ehmicky** [comment]
Did this fix your problem?

**Comment by kripod** [comment]
Yes, it did, as seen in the [build log](https://app.netlify.com/sites/exigo/deploys/5ddfc783d0e69b000889e9f1) and the [deployed site](https://5ddfc783d0e69b000889e9f1--exigo.netlify.com/.netlify/functions/graphql). Unfortunately, queries still fail due to [an issue](https://github.com/prisma-labs/nexus-prisma/issues/546) with nexus-prisma.

**Comment by ehmicky** [comment]
Awesome that it fixed you problem (except for the issue with nexus-prisma)!
Don't hesitate to join our Build Beta (if you haven't yet), as there are several bug fixes related to Netlify Functions which are included in it. :)
