### ISSUE TITLE
Use pure ES modules

### ISSUE THREAD

**Issue by ehmicky** [netlify/zip-it-and-ship-it#749]
See background at https://github.com/netlify/team-dev/issues/36

Once https://github.com/netlify/zip-it-and-ship-it/issues/748 is done and released, we should use pure ES modules and make a major release.

This is more than just switching from CommonJS to `import`/`export`. See [this list](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) for other changes which might be involved. This should be broken in many PRs, as much as possible, to lower the risk. Also, non-breaking changes (such as adding file extensions in imports, or loading JSON files differently) should be done before the breaking changes (such as using `import`/`export` statements).

This should only be done after pure ES modules are supported in both Netlify CLI (https://github.com/netlify/cli/issues/3514) and Netlify Build (https://github.com/netlify/build/issues/3742).

**Comment by ehmicky** [comment]
I have opened several PRs to tackle most of the problems related to migrating to pure ES modules:
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/970
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/971
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/972
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/973
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/974
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/975
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/976
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/977
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/978
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/979
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/980
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/981
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/982
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/983
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/984
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/985
  - [ ] https://github.com/netlify/zip-it-and-ship-it/pull/986

Two problems are still pending:
  - [ ] Several dependencies are currently missing their types when using the new TypeScript `nodenext` option. I am currently using `@ts-ignore` comments, but am considering switching to using `declare` statements in a `*.d.ts` instead.
  - [ ] `esbuild` is adding some ES modules-specific test helpers to Netlify Functions, even if they use CommonJS, if this repository's switches to pure ES modules. 

The following PR is the final PR which does the actual migration: https://github.com/netlify/zip-it-and-ship-it/pull/965. It includes all of the PRs above, plus the actual migration. Since each of those changes carries some risk with it, the PR are marked with `fix:` so we can release those incrementally.

**Comment by brittneypostma** [comment]
Any progress on this? It's blocking a `adapter-netlify` update for SvelteKit.

**Comment by danez** [comment]
This is only about releasing zisi as esm module, this has nothing to do with how we bundle functions. What you are probably looking for is https://github.com/netlify/zip-it-and-ship-it/issues/750

The linked svelte kit issue might have been fixed with https://github.com/sveltejs/kit/pull/6666 from @eduardoboucas, but not sure.
