### ISSUE TITLE
Add support for assets not mentioned in `files` of `package.json`

### ISSUE THREAD

**Issue by timsuchanek** [netlify/zip-it-and-ship-it#77]
While `zip-it-and-ship-it` right now supports resolving `require` statements, if I have a `path.join(__dirname, 'somefile')` statement, it gets ignored by `zip-it-and-ship-it`, therefore if a package ships some assets, which are not mentioned in `files` of the package.json, they're not included by the packing algorithm.

With Photon.js, we're downloading binary files in the `postinstall` hook of the package. These files right now are ignored by `zip-it-and-ship-it`, making Photon.js broken in Netlify functions.

Note: The binaries are not mentioned in the `files` field of our package.json, as we don't want to ship the binaries when publishing. Instead, they're downloaded in the `postinstall` hook of the `@prisma/photon` package.

I see a couple of options here:

1. Give package authors an explicit way to add files in addition to `files`.
This option would, however, require a custom standard, library authors shouldn't really have to bother about concrete deployment targets like Netlify.

2. Just copy over the whole packages, not just what's mentioned in the `files` part.

3. Use smart logic like [node-file-trace](https://github.com/zeit/node-file-trace) does (it's used in Zeit Now).
Photon.js is compatible with `node-file-trace`, by adding `path.join(path to binary)` statements in the code, which are recognized by `node-file-trace`.

The first step for this smart logic could basically be, including not only the `require` statements of a file, but also the `path.join` / `path.resolve` statements.

A quick fix could, of course, be having a union of what you have today and the files that `node-file-trace` suggests.

I know that you're having a beta implementation, which may have tackled this already, but I don't have access to the build beta yet. I just filled the beta form, in case that's needed.

Thanks!

**Comment by timsuchanek** [comment]
Update: It looks like https://github.com/netlify/zip-it-and-ship-it/pull/48/files#diff-6ff379484cbabad48301d485db111c08R48 should solve this. Now I just need to know how to try the beta 🙂

**Comment by ehmicky** [comment]
Hi @timsuchanek, thanks for reaching out!

For reference purpose, I believe you are speaking about the following [`postinstall` script](https://github.com/prisma/photonjs/blob/262d68e38bc5c8d41e69329acdcd294648e29050/packages/photon/package.json#L13) which triggers the [following file](https://github.com/prisma/photonjs/blob/master/packages/photon/scripts/generate.js). Could you please print a tree of files that are typically generated by this Node file?

Please note also that the problem you are mentioning are `path.join()` is a broader issue: we do not currently support dynamic `require()`, for example when the path is not a string constant (which is your case) or when put inside a `if` block. I've opened #68 for this specific problem, feel free to provide with some feedback on this.

As you correctly pointed out, the beta should include a fix for your particular issue (with a variation of your `2.` solution. I am going to make sure you're included in our beta so you can make sure Photon.js and Netlify Functions work well together :+1: 

I will bump this issue once you have access :)

**Comment by timsuchanek** [comment]
> For reference purpose, I believe you are speaking about the following postinstall script which triggers the following file .
100% Correct!
Yes, the files that are already shipped with the `@prisma/photon` package and are correctly packaged already by Netlify are these:
https://photonjs-324-test.netlify.com/.netlify/functions/hello-facade

The files, which are generated on top in `node_modules/@prisma/photon`:
`index.js`
`index.d.ts`
`runtime/query-engine-PLATFORM` Where PLATFORM can e.g. be `darwin` or in netlifys case `rhel-openssl-1.0.x`.

**Comment by ehmicky** [comment]
Yes I can confirm should be packaged with the Netlify Build Beta. I will let you know once you're in! :)

**Comment by timsuchanek** [comment]
I just tried it out with the build beta - it works!

**Comment by ehmicky** [comment]
Amazing Tim! Feel free to send us more feedback about the Beta on `netlify/zip-it-and-ship-it` (for Netlify Functions) and on `netlify/build` (for the rest). :+1:
