### ISSUE TITLE
NPM modules missing

### ISSUE THREAD

**Issue by DavidWells** [netlify/zip-it-and-ship-it#80]
IIRC some updates to zip & ship made sure that function modules were automatically installed.

It doesn't look like this is the case with `0.4.0-8` 

See build logs: https://app.netlify.com/sites/functions/deploys/5e28e2a39ad3e7000a0d9f25

```
4:03:52 PM: Prepping functions with zip-it-and-ship-it 0.4.0-8
4:03:53 PM: Error: In file "/opt/build/repo/functions/add-example.js": Cannot find module 'git-url-parse/package.json' from '/opt/build/repo/functions'
4:03:53 PM: Error prepping functions
```

Src code of functions is here https://github.com/netlify-labs/functions-site/tree/8be620d771cc048dbab6bb302f1fd844fb3d5636/functions

`ZISI_VERSION` env var set to `0.4.0-8`

**Comment by maggo** [comment]
Same issue when trying to deploy a function with `next@9.2.1` dependency:
```
4:41:05 PM: Prepping functions with zip-it-and-ship-it 0.4.0-8
4:41:07 PM: Error: In file "/opt/build/repo/dist/functions/netlify/nextApp/nextApp.js": Cannot find module 'node-sass/package.json' from '/opt/build/repo/node_modules/sass-loader'
4:41:07 PM: Error prepping functions
```

sass-loader has them defined as peerDependencies https://github.com/webpack-contrib/sass-loader/blob/master/package.json

**Comment by DavidWells** [comment]
> Adding node-sass, sass, fibers as dev dependencies fixes it

Interesting! Thanks for debugging that bit. Looks like we will need to account for this in the bundling resolution

**Comment by ehmicky** [comment]
@DavidWeels, this seems to be a problem with the current production version too (`0.3.1`). I cloned the repository and removed the `ZISI_VERSION` environment variable and [got the same error](https://app.netlify.com/sites/lucid-jepsen-560d48/deploys/5e2b511fe3b729d764f67484).

@maggo, could you please try removing the `ZISI_VERSION` environment variable and check if you still get the error? Just to debug whether this is the same issue or a separate one.

**Comment by ehmicky** [comment]
Closing this issue as this is stale. Feel free to re-open if this is still happening.
