### ISSUE TITLE
This does not work with Prisma

### ISSUE THREAD

**Issue by divyenduz** [netlify/zip-it-and-ship-it#81]
**Describe the bug**

The same project with GH integration works but doesn't work with `netlify build` and `netlify deploy` command combination. 

Prisma client requires latest version of ZISI (ZISI_VERSION=0.4.0-8) as it contains this fix https://github.com/netlify/zip-it-and-ship-it/issues/77

**Steps to reproduce**

Reproduction repository https://github.com/divyenduz/netlify-ci-build
The repo readme has all the context and reproduction steps. 

**Expected behavior**

GH integration and `netlify build && netlify deploy` should be identical. 

**Configuration**

As mentioned in the reproduction repo's readme, both projects use netlify's beta build. 

**Environment**

Enter the following command in a terminal and copy/paste its output:

```bash
divyendusingh [platforms]$ npx envinfo --system --binaries --npmPackages @netlify/build,@netlify/config,@netlify/git-utils,@netlify/cache-utils,@netlify/functions-utils,@netlify/run-utils,netlify-cli
npx: installed 1 in 1.265s

  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 755.51 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.8.0/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Screenshots**

https://github.com/divyenduz/netlify-ci-build

**Can you submit a pull request?**

No. Because possibly internal code :)

**Comment by divyenduz** [comment]
So, in my case, the binary files were present in the `node_modules` after the `postinstall` hook or `prisma2 generate` is run. 

The green ones are the required binaries 

![image](https://user-images.githubusercontent.com/746482/73178438-8af84f80-4111-11ea-8b53-ec43116ee114.png)

They are also present in the bundled function (my original assumption about zip-it-and-ship it were wrong). I extracted the zip and could see them in the ls. 

![image](https://user-images.githubusercontent.com/746482/73178860-6a7cc500-4112-11ea-8414-54a09dbdeaab.png)

But at runtime, I get this error: `Query engine binary for current platform rhel-openssl-1.0.x could not be found.\nPrisma Client looked in /var/task/node_modules/@prisma/client/runtime/query-engine-rhel-openssl-1.0.x`

Which makes me believe, that the unzip + moving these files to /var/task/node_modules is missing copying the binaries. 

**Is there a way for me to test this and/or get more visibility into this? Could you validate this?**

Note that the same codebase works with the GH integration of netlify. Are there any differences in the unzip logic between `netlify deploy` command vs the GH integration? 

---

> Also, thanks for the demo repository. Is there any chance you could reduce its size? If not, no worries, what matters is that it's reproducible :)

What do you mean by reducing its size?

**Comment by divyenduz** [comment]
So, I went ahead and did some more logging (`sh run.sh` as the `command` in `netlify.toml` that logs the contents of the current directory), this is a snapshot from the GH integration CI (where it works). 

![image](https://user-images.githubusercontent.com/746482/73180378-859d0400-4115-11ea-8a32-a6a47a05a25d.png)

I am not sure though what is the difference between this vs `netlify build` and deploy but at some point (my hunch is after unpacking) the binaries don't exist anymore.

**Comment by divyenduz** [comment]
I also logged at runtime the following information: `__dirname`, `ls`, `ls node_modules/@prisma/client/runtime | grep query-engine`

and as I expected, there are no binaries in the case where it doesn't work (`netlify build && netlify deploy --prod`)

![image](https://user-images.githubusercontent.com/746482/73185435-563ec500-411e-11ea-803b-21906662b96a.png)

and the binaries exist in the case where it works (GH integration)

![image](https://user-images.githubusercontent.com/746482/73185673-c6e5e180-411e-11ea-9a9b-0b5e26a7a72b.png)

--- 

Interesting to note that the two deployment methods have different folder structure and `__dirname`. They should be identical right? 

I hope this information helps you in helping us.

**Comment by heymartinadams** [comment]
@divyenduz running into the same issue when attempting a deploy:
```console
"Error: 
Invalid `prisma.user.update()` invocation in
/var/runtime/Runtime.js:66:25

Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/query-engine-rhel-openssl-1.0.x")

You already added the platforms "native", "rhel-openssl-1.0.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma-client-js/issues/new"
```

Meanwhile, my `netlify.toml` file contains the following. Might you know what I’m missing?

```toml
[build]
command = "yarn beta"
functions = "build-functions/"
publish = "build/"

[build.environment]
# Fix to ensure the Prisma binary is packaged with the lambda function
ZISI_VERSION = "0.4.0-9"
```

Using the latest Prisma CLI and client `preview025` (released today).

**Comment by heymartinadams** [comment]
ps: I should be saying that I’m using Github integration.

**Comment by divyenduz** [comment]
Can you try to rename your command from `beta` to `build`?

**Comment by heymartinadams** [comment]
@divyenduz already opened up a new issue [here](https://github.com/prisma/prisma/issues/2082).

**Comment by ehmicky** [comment]
Is this issue closed by [this](https://github.com/netlify/build/issues/730#issuecomment-615177926)?
@divyenduz @timsuchanek

**Comment by divyenduz** [comment]
I think so yes 🙌
