### ISSUE TITLE
Return `schedule` from `listFunctions`

### ISSUE THREAD

**Issue by netlify-team-account-1** [netlify/zip-it-and-ship-it#833]
netlify/cli wants to show a `schedule` column as part of the result of `ntl functions:list`. [It currently uses `listFunctions`](https://github.com/netlify/cli/blob/53643b43d79b8c0b569c797d366f3041cae062e3/src/utils/get-functions.js#L23) to obtain the list of functions, but that return value doesn't contain the `schedule` field. We should add it.

If that shows to be a bigger lift, we can work around it by using `zipFunctions` in the meantime.

**Comment by eduardoboucas** [comment]
I think this will pose some challenges, especially once we introduce in-source config declarations, which can only be picked up when we do the parsing. `zipFunctions` triggers the parsing stage, `listFunctions` doesn't.

I'm not against using `zipFunctions` for this, but calling this creates a bunch of ZIP files, which isn't expected for a read operation. We need to figure out what to do about that.

Added to Triage.

**Comment by netlify-team-account-1** [comment]
will be closed by #899
