### ISSUE TITLE
Size optimisation suggestion: Do not include `@types/*` node modules

### ISSUE THREAD

**Issue by peterp** [netlify/zip-it-and-ship-it#86]
`@types/*` is the 3rd largest directory of modules in my zipped lambda function.

I think they might only be helpful during development and could potentially be ignored by zip-it-and-ship-it.

**Comment by erquhart** [comment]
From the readme:
> Zip It and Ship It will only include dependencies in each zip file that's been required from the relevant handler file.

@ehmicky since types wouldn't be explicitly required in the function source, shouldn't we be excluding them already?

**Comment by peterp** [comment]
Let me verify this; I might have been using an older version of ZiSi.

**Comment by ehmicky** [comment]
`zip-it-and-ship-it` works in several passes:
  1. Detect all `require()` statements in Netlify Functions
  2. Bundle the published files of those node modules
  3. Find the `package.json` of those node modules, and recurse over their `dependencies`

For the last step, we definitely should exclude any package whose name starts with `@types/` :+1:

**Comment by ehmicky** [comment]
Done in #99
