### ISSUE TITLE
Performance issues with new versions of `@babel/parser`

### ISSUE THREAD

**Issue by ehmicky** [netlify/zip-it-and-ship-it#968]
Some builds are experiencing a big slowdown when we [upgrade `@babel/parser`](https://github.com/babel/babel/blob/main/packages/babel-parser/README.md) from [`7.16.8`](https://github.com/babel/babel/releases/tag/v7.16.8) to [`7.16.10`](https://github.com/babel/babel/releases/tag/v7.16.10) (note: there is no `7.16.9` release).

We are currently unable to reproduce this locally. However, @eduardoboucas and I are able to reproduce this in production using [the following Netlify site](https://app.netlify.com/sites/relaxed-khorana-626979).

The only PR introduced by that release is https://github.com/babel/babel/pull/14130, so it appears to be the reason. Two bugs related to that PR are open, which could be the root cause, but we are not sure yet: https://github.com/babel/babel/issues/14182, https://github.com/babel/babel/issues/14175

From extensive debugging, we are certain that the problem comes from this specific package and this specific version. We also know the problem comes from `@babel/parser` as a direct dependency of `@netlify/zip-it-and-ship-it` (see [this](https://github.com/netlify/zip-it-and-ship-it/blob/440467162fde5ee5e8f140721a1a7ed574c49e6e/package.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L55) and [that](https://github.com/netlify/zip-it-and-ship-it/blob/440467162fde5ee5e8f140721a1a7ed574c49e6e/src/runtimes/node/parser/index.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L5)), as opposed to as an indirect dependency through `precinct` (see [this](https://github.com/netlify/zip-it-and-ship-it/blob/440467162fde5ee5e8f140721a1a7ed574c49e6e/package.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L77) and [that](https://github.com/netlify/zip-it-and-ship-it/blob/440467162fde5ee5e8f140721a1a7ed574c49e6e/src/runtimes/node/bundlers/zisi/src_files.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L5)) and `node-source-walker` (see [this](https://github.com/dependents/node-precinct/blob/271943ef748f05a0631543408d39fcec2dd47dc3/index.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L8) and [that](https://github.com/dependents/node-source-walk/blob/87c4f337286107d1f6585b3fbb74d50789f24a50/index.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1)).

The problem only impacts our legacy bundler, not the `nft` nor `esbuild` bundlers.

We have made a PR, now released, which pins the version of `@babel/parser` to `7.16.8` as a way to mitigate the problem: https://github.com/netlify/zip-it-and-ship-it/pull/966

However, this is not a long-term solution because it prevents us from upgrading `@babel/parser` in the future, which we might need to do for compatibility with the latest JavaScript syntax, or for security fixes. I see several possible long-term solutions there:
  1. Keep the old version of `@babel/parser` until we fully deprecate the legacy bundler.
  2. Follow the existing bug reports and new versions of `@babel/parser` hoping they fix this problem.
  3. Find the reason why this new version of `@babel/parser` is creating an issue with our code in this repository. Only 4 files are using this, so it might be doable, or at least worth some investigation.

@eduardoboucas @Skn0tt @minivan What are your thoughts on this?

**Comment by eduardoboucas** [comment]
I think we should keep the old version of `@babel/parser` for the time being, unless we find a strong reason to upgrade (like a bug or a missing feature).

**Comment by nicolo-ribaudo** [comment]
This might have been fixed in Babel 7.17.0 by https://github.com/babel/babel/pull/14174.
